language: python
python:
 - "2.6"
 - "2.7"
 - "3.0"
install:
 - "pip install -e ."
 - "pip install coverage coveralls"
script:
 - "coverage run `which django-admin.py` test django_prbac --settings django_prbac.mock_settings --traceback"
after_success:
 - coverage report
 - coveralls

