language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
install:
 - "pip install -e ."
 - "pip install coverage coveralls"
script:
 - "coverage run django-admin.py --settings django_prbac.mock_settings test"
after_success:
 - coverage report
 - coveralls

